apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-app-deployment
  namespace: default
##  namespace: pets-app-namespace
  labels:
    app: pets-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pets-app-deployment
  template:
    metadata:
      labels:
        app: pets-app-deployment
    spec:
      containers:
        - name: pets-app-deployment
          image: us.gcr.io/wired-rex-393519/pet-clinic:1.0.2
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP

