apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-app-deployment
  namespace: pets-app-namespace
  labels:
    app: pets-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pets-app-deployment
  template:
    metadata:
      labels:
        app: pets-app-deployment
    spec:
      containers:
        - name: pets-app-deployment
          image: michaelssss88/pet-clinic:1.0.0
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP

