apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-app-deployment
  labels:
    app: pets-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pets-app-deployment
  template:
    metadata:
      labels:
        app: pets-app-deployment
    spec:
      containers:
        - name: pet-clinic-image
          image: us.gcr.io/wired-rex-393519/pet-clinic:1.0.3
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP

