apiVersion: v1
kind: Service
metadata:
  name: pets-app-service-node-port
  namespace: default
##  namespace: pets-app-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pets-app-deployment

##Important commands to test service locally.
##kubectl run alpine --image alpine:3.12 --command -- sleep 3600 -n pets-app-namespace.yaml
##kubectl -n pets-app-namespace exec -it alpine -- apk --update add curl
##kubectl -n pets-app-namespace exec alpine -- curl http://10.244.0.67:8080/vets.html //

##Save to google repo
##docker push us-docker.pkg.dev/wired-rex-393519/us.gcr.io/pet-clinic

##Get from google repo
##docker pull us-docker.pkg.dev/wired-rex-393519/us.gcr.io/pet-clinic

