apiVersion: v1
kind: Service
metadata:
  name: pets-app-service
  namespace: pets-app-namespace
spec:
  type: ClusterIP
  ports:
    - name: web-service
      port: 8080
      targetPort: 8080
  selector:
    app: pets-app-deployment

##Important commands to test service locally.
##kubectl run alpine --image alpine:3.12 --command -- sleep 3600 -n pets-app-namespace.yaml
##kubectl -n pets-app-namespace exec alpine -- curl http://10.244.0.67:8080/vets.html //