apiVersion: v1
kind: Pod
metadata: 
  name: quota-men-cpu-demo
spec:
  containers:
  - name: quota-men-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests: 
        memory: "600Mi"
        cpu: "400m"
