apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: class2
  labels:
    app: class2-pet-clinic
    tier: class2
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: class2
  template:
    metadata:
      labels:
        tier: class2
    spec:
      containers:
        - name: pet-clinic
          image: michaelssss88/pet-clinic:1.0.0
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP

#apiVersion: apps/v1
#kind: ReplicaSet
#metadata:
#  name: frontend
#  labels:
#    app: guestbook
#    tier: frontend
#spec:
#  # modifica las réplicas según tu caso de uso
#  replicas: 3
#  selector:
#    matchLabels:
#      tier: frontend
#  template:
#    metadata:
#      labels:
#        tier: frontend
#    spec:
#      containers:
#        - name: php-redis
#          image: gcr.io/google_samples/gb-frontend:v3