apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
  labels:
    app: app-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app-deployment


    